export const mockSTTStore = {
  endpoint: 'silero',
  endpointSilenceMs: 700,
  autoSubmit: true,
  asrEngine: 'moonshine',
  sessionState: {mode: 'idle'},
  partialText: '',
  finalText: '',
  lastError: null,
  modelsInstalled: false,
  isInstallingModels: false,
  modelDownloadProgress: 0,
  isSTTEnabled: true,
  isListening: false,
  init: jest.fn().mockResolvedValue(undefined),
  start: jest.fn().mockResolvedValue(undefined),
  stop: jest.fn().mockResolvedValue(undefined),
  installModels: jest.fn().mockResolvedValue(undefined),
  clearFinalText: jest.fn(),
};
